/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stations */
        get: operations["get_stations_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Stations For Role Switcher
         * @description Unscoped station directory — feeds the demo Role Switcher dropdown, which needs
         *     to list every station a judge could pretend to log in as. Not used for data reads.
         */
        get: operations["get_all_stations_for_role_switcher_stations_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect */
        post: operations["detect_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offenders */
        get: operations["offenders_offenders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph */
        get: operations["graph_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suspects/{suspect_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suspect Dossier */
        get: operations["suspect_dossier_suspects__suspect_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CrimeCategoryCount */
        CrimeCategoryCount: {
            /** Crime Category */
            crime_category: string;
            /** Count */
            count: number;
        };
        /** DashboardSummaryOut */
        DashboardSummaryOut: {
            /** Total Firs */
            total_firs: number;
            /** Total Suspects */
            total_suspects: number;
            /** Total Clusters */
            total_clusters: number;
            /** Total Syndicates */
            total_syndicates: number;
            /** By Crime Category */
            by_crime_category: components["schemas"]["CrimeCategoryCount"][];
            /** By Station */
            by_station: components["schemas"]["StationCount"][];
        };
        /** DetectResponse */
        DetectResponse: {
            /** Clusters Created */
            clusters_created: number;
            /** Syndicates Flagged */
            syndicates_flagged: number;
            /** Inter District Mo Edges */
            inter_district_mo_edges: number;
        };
        /** GraphLink */
        GraphLink: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Meta */
            meta?: Record<string, never>;
        };
        /** GraphOut */
        GraphOut: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Links */
            links: components["schemas"]["GraphLink"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestItem */
        IngestItem: {
            /** Raw Text */
            raw_text: string;
            /** Station Id */
            station_id?: number | null;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Items */
            items: components["schemas"]["IngestItem"][];
        };
        /** IngestResponse */
        IngestResponse: {
            /** Ingested */
            ingested: components["schemas"]["IngestResultItem"][];
            /** Failed */
            failed: Record<string, never>[];
        };
        /** IngestResultItem */
        IngestResultItem: {
            /** Fir Id */
            fir_id: number;
            /** Fir Number */
            fir_number: string;
            /** Station Id */
            station_id: number;
            /** Crime Category */
            crime_category: string;
            /** Extraction Source */
            extraction_source: string;
            /** Suspects Extracted */
            suspects_extracted: number;
        };
        /** OffenderClusterOut */
        OffenderClusterOut: {
            /** Canonical Id */
            canonical_id: string;
            /** Primary Name */
            primary_name: string;
            /** Linked Fir Ids */
            linked_fir_ids: number[];
            /** Districts Involved */
            districts_involved: string[];
            /** Confidence Score */
            confidence_score: number;
            /** Match Reasons */
            match_reasons: string[];
            /** Syndicate Flag */
            syndicate_flag: boolean;
        };
        /** StationCount */
        StationCount: {
            /** Station Id */
            station_id: number;
            /** Station Name */
            station_name: string;
            /** Count */
            count: number;
        };
        /** StationOut */
        StationOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** District */
            district: string;
            /** Zone */
            zone: string;
            /** State */
            state: string;
        };
        /** SuspectDossierOut */
        SuspectDossierOut: {
            /** Suspect Id */
            suspect_id: number;
            /** Name */
            name: string | null;
            /** Aliases */
            aliases: string[];
            /** Phone Numbers */
            phone_numbers: string[];
            /** Vehicle Numbers */
            vehicle_numbers: string[];
            /** Physical Description */
            physical_description: string | null;
            /** Associated Fir Ids */
            associated_fir_ids: number[];
            cluster: components["schemas"]["OffenderClusterOut"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_stations_stations_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-Role": string;
                "X-User-Station"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_stations_for_role_switcher_stations_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationOut"][];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectResponse"];
                };
            };
        };
    };
    dashboard_summary_dashboard_summary_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-Role": string;
                "X-User-Station"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offenders_offenders_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-Role": string;
                "X-User-Station"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OffenderClusterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_graph_get: {
        parameters: {
            query?: never;
            header: {
                "X-User-Role": string;
                "X-User-Station"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspect_dossier_suspects__suspect_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-User-Role": string;
                "X-User-Station"?: number | null;
            };
            path: {
                suspect_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuspectDossierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
